---
name: Build & Deploy Website

on:
  workflow_call:
    secrets:
      REPO_GITHUB_TOKEN:
        description: |
          Github token with write access to the repository
        required: false
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "10 10 * * *"
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build & Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache artifacts
        uses: actions/cache@v4
        with:
          path: _freeze
          key: ${{ runner.os }}-examples

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish docs
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
